project:
  type: website

website:
  title: "Lee C. Mercer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

