project:
  type: website

website:
  title: "// Lee C. Mercer"
  image: me.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://bkst.quarto.pub/blankstate/
        text: Blog
      - about.qmd
  twitter-card: True
  page-footer: 
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

