---
title: "Curriculum Vitae"
subtitle: "Lee C. Mercer"
date: "`r Sys.Date()`"
format:
    pdf: default
    html: 
      self-contained: true


reference-location: margin
citation-location: margin
bibliography: skeleton.bib
---

# Lee C. Mercer

Research Assistant

::: column-margin
### About Lee

An experienced NHS manager, with over a decade of in leadership roles. Following the adoption of our two children, a high achieving student awarded a First in my Psychology BSc. Currently in the final year of a Health Psychology MSc.
:::

## Summary of experience

### 2022 - present

**Research Assistant**\
*University of Bath*

Survey research design // Recruiting survey volunteers // Ethics application // Drafting a scoping protocol // Supporting a research team // Writing a dissertation

### 2018-2022

**Career break & Study**\

Primary carer to young children // Psychology BSc // Volunteer - Barnardos, Shout // Health Psychology MSc

### 2015-2018

**Strategic leadership roles**\
*Avon & Wiltshire Mental Health Partnership NHS Trust*\

Strategic transformation // Corporate governance // Risk management // Legal services.

### 2003-2018

**Patient Safety, risk and legal services**\
*University Hospitals Bristol NHS Foundation Trust*\
*Great Western Hospitals NHS Foundation Trust*

------------------------------------------------------------------------

::: column-margin
### Key skills

-   Team working
-   Communication
-   Problem solving
-   Research methods
:::

## Main Column Figures

Besides margin and full width figures, you can of course also include figures constrained to the main column. This is the default type of figures in the LaTeX/HTML output.

## Margin Captions

When you include a figure constrained to the main column, you can choose to place the figure's caption in the margin by using the `cap-location` chunk option. For example:

# Sidenotes

One of the most prominent and distinctive features of this style is the extensive use of sidenotes. There is a wide margin to provide ample room for sidenotes and small figures. Any use of a footnote will automatically be converted to a sidenote.

[This is a span that has the class `column-margin` which places it in the margin without the sidenote mark.]{.column-margin} If you'd like to place ancillary information in the margin without the sidenote mark (the superscript number), you can use apply the `column-margin` class to the element.

::: {.callout-note appearance="simple"}
Shout is a 24/7 text-based Crisis service staffed by volunteers. It was established in XXXX.
:::

# Tables

You can use the `kable()` function from the **knitr** package to format tables that integrate well with the rest of the Tufte handout style. The table captions are placed in the margin like figures in the HTML output.

## Volunteering

| Year      | Role                                  | Organisation                     ||-------------|------------------------------|------------------------------|
| 2017-2019 | Toddler & parent group support worker | Barnardos (www.barnardos.org.uk) |
| 2021      | Child and adolescent mental health    | Barnados (www.barnardos.org.uk)  |
| 2021      | Crisis text line volunteer            | Shout (www.giveusashout.org.uk)  |

### 2017 - 2019

**Toddler group support**\
Barnardo's (www.barnardos.org.uk/)

2021 Children and adolescent mental health training Barnardo's (www.barnardos.org.uk/) 2021 Crisis text line volunteer Shout (www. giveusashout.org.uk)

## Interests

## Full employment history

## Contact
